config/routes.rb
Gitlab::Application.routes.draw do
  resources :projects, :only => [:new, :create, :index]

  resources :projects, :except => [:new, :create, :index], :path => "/" do 
    member do 
      get "tree"
      get "blob"
      get "wall"

      # tree viewer
      get "tree/:commit_id" => "projects#tree"
      get "tree/:commit_id/:path" => "projects#tree",
      :as => :tree_file,
      :constraints => { 
        :id => /[a-zA-Z0-9]+/,
        :commit_id => /[a-zA-Z0-9]+/,
        :path => /.*/
      }

    end
    resources :commits
    resources :notes, :only => [:create, :destroy]
  end
  root :to => "projects#index"
end

app/models/project.rb
require "grit"

class Project < ActiveRecord::Base
  has_many :notes, :dependent => :destroy

  validates :name,
            :uniqueness => true,
            :presence => true,
            :length   => { :within => 0..255 }

  validates :path,
            :uniqueness => true,
            :presence => true,
            :length   => { :within => 0..255 }
  
  validates :description,
            :length   => { :within => 0..2000 }

  validates :code,
            :presence => true,
            :uniqueness => true,
            :length   => { :within => 3..12 }

  before_save :format_code

  attr_protected :private_flag, :owner_id

  scope :public_only, where(:private_flag => false)

  def to_param
    code
  end

  def common_notes
    notes.where(:noteable_type => ["", nil])
  end

  def format_code
    read_attribute(:code).downcase.strip.gsub(' ', '')
  end

  def public?
    !private_flag
  end

  def private?
    private_flag
  end

  def url_to_repo
    path
  end
  
  def path_to_repo
    path
  end

  def repo 
    @repo ||= Grit::Repo.new(path_to_repo)
  end

  def tags
    repo.tags.map(&:name).sort.reverse
  end

  def repo_exists?
    repo rescue false
  end

  def commit(commit_id = nil)
    if commit_id
      repo.commits(commit_id).first
    else 
      repo.commits.first
    end
  end

  def tree(fcommit, path = nil)
    fcommit = commit if fcommit == :head
    tree = fcommit.tree
    path ? (tree / path) : tree
  end

  def valid_repo?
    repo
  rescue
    errors.add(:path, "Invalid repository path")
    false
  end
end
# == Schema Information
#
# Table name: projects
#
#  id           :integer         not null, primary key
#  name         :string(255)
#  path         :string(255)
#  description  :text
#  created_at   :datetime
#  updated_at   :datetime
#  private_flag :boolean         default(TRUE), not null
#  code         :string(255)
#  owner_id     :integer
#

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :project, :except => [:index, :new, :create] 

  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  def show
    @repo = project.repo
    @commit = @repo.commits.first
    @tree = @commit.tree
    @tree = @tree / params[:path] if params[:path]

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: project }
    end
  rescue Grit::NoSuchPathError => ex
    respond_to do |format|
      format.html {render "projects/empty"}
    end
  end

  def tree
    @repo = project.repo
    @branch = if !params[:branch].blank?
                params[:branch]
              elsif !params[:tag].blank?
                params[:tag]
              else
                "master"
              end

    if params[:commit_id]
      @commit = @repo.commits(params[:commit_id]).first
    else 
      @commit = @repo.commits(@branch || "master").first
    end
    @tree = @commit.tree
    @tree = @tree / params[:path] if params[:path]

    respond_to do |format|
      format.html # show.html.erb
      format.js do 
        # temp solution
        response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
        response.headers["Pragma"] = "no-cache"
        response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
      end
      format.json { render json: project }
    end
  end

  def blob
    @repo = project.repo
    @commit = project.commit(params[:commit_id])
    @tree = project.tree(@commit, params[:path])

    if @tree.is_a?(Grit::Blob)
      send_data(@tree.data, :type => @tree.mime_type, :disposition => 'inline', :filename => @tree.name)
    else 
      head(404)
    end
  end

  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  def edit
  end

  def create
    @project = Project.new(params[:project])
    @project.save!

    respond_to do |format|
      if @project.valid?
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.js 
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.js
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  rescue Gitosis::AccessDenied
    render :js => "location.href = '#{errors_gitosis_path}'" and return
  rescue StandardError => ex
    @project.errors.add(:base, "Cant save project. Please try again later")
    respond_to do |format|
      format.html { render action: "new" }
      format.js
      format.json { render json: @project.errors, status: :unprocessable_entity }
    end
  end

  def update
    respond_to do |format|
      if project.update_attributes(params[:project])
        format.html { redirect_to project, notice: 'Project was successfully updated.' }
        format.js 
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.js 
        format.json { render json: project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :ok }
    end
  end

  def wall
    @notes = @project.common_notes
    @note = Note.new
  end

  protected 

  def project 
    @project ||= Project.find_by_code(params[:id])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_side_panel.html.haml
%h3.notice{:style => "width:235px;"}
  = @project.name
%p
  %b Path:
  = @project.path
%p
  %b Description:
  = truncate @project.description
.left.append-bottom
  = link_to "Tree", tree_project_path(@project), :class => "button"
  = link_to "Commits", project_commits_path(@project), :class => "button"
  = link_to 'Team', team_project_path(@project), :class => "button"
  - if can? current_user, :admin_project, @project
    = link_to 'Edit', edit_project_path(@project), :class => "button positive"

app/views/projects/_top_menu.html.haml
%div.top_project_menu
  - if @project.repo_exists?
    %span= link_to "Tree", tree_project_path(@project), :class => current_page?(:controller => "projects", :action => "show", :id => @project) || current_page?(:controller => "projects", :action => "tree", :id => @project) ? "current" : nil
    %span= link_to "Commits", project_commits_path(@project), :class => current_page?(:controller => "commits", :action => "index", :project_id => @project) ? "current" : nil
  %span
    = link_to wall_project_path(@project), :class => current_page?(:controller => "projects", :action => "wall", :id => @project) ? "current" : nil do
      Wall
      - if @project.common_notes.count > 0
        %span{ :class => "top_menu_count" }= @project.common_notes.count

  - if @commit
    %span= link_to truncate(commit_name(@project,@commit), :length => 15), project_commit_path(@project, :id => @commit.id), :class => current_page?(:controller => "commits", :action => "show", :project_id => @project, :id => @commit.id) ? "current" : nil

app/views/projects/_tree.html.haml
%h3
  .left
    = form_tag tree_project_path(@project), :method => :get do
      = select_tag "branch", options_for_select(@repo.heads.map(&:name), @branch), :onchange => "this.form.submit();", :class => "", :prompt => "Branches"
  &nbsp;
  .left.prepend-1
    = form_tag tree_project_path(@project), :method => :get do
      = select_tag "tag", options_for_select(@project.tags, @branch), :onchange => "this.form.submit();", :class => "", :prompt => "Tags"
  = text_field_tag "ssh", @project.url_to_repo, :class => ["ssh_project_url","one_click_select"]
  .clear

%h3#tree-breadcrumbs
  = link_to @project.name, tree_project_path(@project, :path => nil, :commit_id => @commit.try(:id)), :remote => true
  - if params[:path]
    - part_path = ""
    - params[:path].split("\/").each do |part|
      - part_path = File.join(part_path, part) unless part_path.empty?
      - if part_path.empty?
        - part_path = part
      \/
      = link_to truncate(part, :length => 40), tree_file_project_path(@project, :path => part_path, :commit_id => @commit.try(:id)), :remote => :true
#tree-content-holder
  - if tree.is_a?(Grit::Blob)
    = render :partial => "projects/tree_file", :locals => { :name => tree.name, :content => tree.data, :file => tree }
  - else
    - contents = tree.contents
    %table#tree-slider.round-borders
      %tr
        %th Name
        %th Last Update
        %th
          Last commit
          = link_to "history", project_commits_path(@project, :path => params[:path]), :class => "right"
      - if params[:path]
        - file = File.join(params[:path], "..")
        %tr{ :class => "tree-item", :url => tree_file_project_path(@project, @commit.id, file) }
          %td.tree-item-file-name
            = image_tag "dir.png"
            = link_to "..", tree_file_project_path(@project, @commit.id, file), :remote => :true
          %td 
          %td 

      - contents.select{ |i| i.is_a?(Grit::Tree)}.each do |content|
        = render :partial => "projects/tree_item", :locals => { :content => content }
      - contents.select{ |i| i.is_a?(Grit::Blob)}.each do |content|
        = render :partial => "projects/tree_item", :locals => { :content => content }

:javascript
  $(function(){
    $('select#branch').selectmenu({style:'popup', width:200});
    $('select#tag').selectmenu({style:'popup', width:200});
  });

- if params[:path] && request.xhr?
  :javascript 
    $(window).unbind('popstate');
    $(window).bind('popstate', function() {
      if(location.pathname.search("tree") != -1) {
        $.ajax({type: "GET", url: location.pathname, dataType: "script"})}
        else { location.href = location.pathname;}});

app/views/projects/_tree_file.html.haml
- require "utils"
.view_file
  .view_file_header
    %strong
      = name
      -#= file.mime_type
      = link_to "raw", blob_project_path(@project, :commit_id => @commit.id, :path => params[:path] ), :class => "right", :target => "_blank"
      = link_to "history", project_commits_path(@project, :path => params[:path]), :class => "right", :style => "margin-right:10px;"
      %br/
  - if file.mime_type =~ /application|text/ && !Utils.binary?(file.data)
    .view_file_content
      - ft = handle_file_type(file.name, file.mime_type)
      :erb
        <%= raw Albino.colorize(content, ft, :html, 'utf-8', "linenos=True") %>
  - elsif file.mime_type =~ /image/
    .view_file_content_image
      %img{ :src => "data:image/jpeg;base64,#{Base64.encode64(file.data)}"}
  - else
    %p 
      %center No preview for this file type

app/views/projects/_tree_item.html.haml
- file = params[:path] ? File.join(params[:path], content.name) : content.name
- content_commit = @project.repo.log(@branch, file, :max_count => 1).last
- return unless content_commit
%tr{ :class => "tree-item", :url => tree_file_project_path(@project, @commit.id, file) }
  %td.tree-item-file-name
    - if content.is_a?(Grit::Blob)
      = image_tag "txt.png"
    - else
      = image_tag "dir.png"
    = link_to truncate(content.name, :length => 40), tree_file_project_path(@project, @commit.id, file), :remote => :true
  %td
    = time_ago_in_words(content_commit.committed_date)
    ago
  %td
    = link_to truncate(content_commit.message, :length => 40), project_commit_path(@project, content_commit)

app/views/projects/create.js.haml
- if @project.valid?
  :plain
    location.href = "#{project_path(@project, :notice => 'Project was successfully created.')}";
- else
  :plain
    $("#new_project").replaceWith("#{escape_javascript(render('form'))}");

app/views/projects/edit.html.erb
<%= render 'form' %>

app/views/projects/empty.html.erb
<div class="">
  <div class="git-empty">
    <h2>No git repo in this dir:</h2>
    <br/>
  </div>
</div>

app/views/projects/index.html.haml
= link_to 'New Project', new_project_path, :class => "lbutton vm"

%table.round-borders#projects-list
  %tr
    %th Name
    %th Path
    %th Code
    %th Actions

  - @projects.each do |project|
    %tr{ :class => "project", :url => project_path(project) }
      %td= project.name
      %td= truncate project.url_to_repo
      %td= project.code
      %td 
        = link_to 'Edit', edit_project_path(project), :class => "lbutton positive"
        = link_to 'Remove', project, :method => :delete, :confirm => "Are you sure?", :class => "lbutton negative"
%br

app/views/projects/new.html.erb
<%= render 'form' %>

app/views/projects/show.html.haml
%div
  %div#tree-holder
    = render :partial => "tree", :locals => {:repo => @repo, :commit => @commit, :tree => @commit.tree}

app/views/projects/tree.html.erb
<div>
  <div id="tree-holder">
    <%= render :partial => "tree", :locals => {:repo => @repo, :commit => @commit, :tree => @tree} %>
  </div>
</div>

app/views/projects/tree.js.haml
:plain
  $("#tree-holder table").hide("slide", { direction: "left" }, 150, function(){ 
    $("#tree-holder").html("#{escape_javascript(render(:partial => "tree", :locals => {:repo => @repo, :commit => @commit, :tree => @tree}))}");
    $("#tree-holder table").show("slide", { direction: "right" }, 150);
  });

app/views/projects/wall.html.haml
= render "notes/notes"