config/routes.rb
Gitlab::Application.routes.draw do
  resources :projects, :only => [:new, :create, :index]

  resources :projects, :except => [:new, :create, :index], :path => "/" do 
    member do 
      get "tree"
      get "blob"
      get "wall"

      # tree viewer
      get "tree/:commit_id" => "projects#tree"
      get "tree/:commit_id/:path" => "projects#tree",
      :as => :tree_file,
      :constraints => { 
        :id => /[a-zA-Z0-9]+/,
        :commit_id => /[a-zA-Z0-9]+/,
        :path => /.*/
      }

    end
    resources :commits
    resources :notes, :only => [:create, :destroy]
  end
  root :to => "projects#index"
end

app/views/layouts/_flash.html.haml
- if alert || notice
  - text = alert || notice
  %div{:style => "display:none", :id => "flash_container"}
    .container
      %center
        %h4= text
  :javascript
    $(function(){
      $("#flash_container").slideDown("slow"); 
      $("#flash_container").click(function(){ 
        $(this).slideUp("slow"); 
      });
      setTimeout("hideFlash()",2000);
    });

    function hideFlash(){
      $("#flash_container").slideUp("slow");
    }

app/views/layouts/_head_panel.html.erb
<div id="header-panel">
  <div class="container">
    <div class="span-24">
      <div class="span-10">
        <%#= image_tag "git.png", :height => 40, :class => "left" %>
        <%#= link_to "gitlab", root_path, :id => "logo" %>
        <span class="search-holder">
          <%= text_field_tag "search", nil, :placeholder => "Search"  %>
        </span>
      </div>
      <div class="right">
        <%= link_to truncate(@project.name, :length => 20), project_path(@project), :class => "current button" if @project && !@project.new_record? %>
        <%= link_to 'Home', root_path, :class => current_page?(root_url) ? "current button" : "button" %>
        <%= link_to 'Projects', projects_path, :class => current_page?(projects_path) ? "current button" : "button" %>
      </div>
    </div>
  </div>
</div>


<%= javascript_tag do %>
  $(function() {
  $("#search" ).autocomplete({
  source: <%= raw search_autocomplete_source %>,
  select: function(event, ui) { location.href = ui.item.url }
  });
  });
<% end %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      GitLab #{" - #{@project.name}" if @project && !@project.new_record?}
    = stylesheet_link_tag 'blueprint/screen', :media => "screen, projection"
    = stylesheet_link_tag 'blueprint/print', :media => "print"
    = stylesheet_link_tag 'blueprint/plugins/buttons/screen', :media => "screen, projection"
    = stylesheet_link_tag 'blueprint/plugins/link-icons/screen', :media => "screen, projection"
    = stylesheet_link_tag 'jquery_ui/jquery-ui-1.8.16.custom', :media => "screen, projection"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %link{:href => "/assets/favicon.png", :rel => "icon", :type => "image/png"}/
    = javascript_tag do
      REQ_URI = "#{request.env["REQUEST_URI"]}";
      REQ_REFFER = "#{request.env["HTTP_REFERER"]}";
  %body#thebody
    = render :partial => "layouts/flash"
    = render :partial => "layouts/head_panel"
    .top_bar.container
      = render :partial => "projects/top_menu" if @project && !@project.new_record?
      = render :partial => "profile/top_menu" if ["keys", "profile"].include?(controller.controller_name)
    #content-container.container
      .span-24
        = yield